#!/usr/bin/env bash

# Ian's Nix Development Environment Flake Initialization Script
# This script initializes a new project directory with a flake.nix file
# and a .envrc file for direnv. It also creates a .gitignore file and
# a .pre-commit-config.yaml file with some basic hooks.
# The script will prompt for the project name and the environment type.
# The environment type can be one of the following:
# - sscript: Lua scripting environment
# - python: Python development environment
# - web: Node.js and Python web development environment
# - rust: Rust development environment
# - go: Go development environment
# - java: Java development environment
#
# - Clones or updates a global nix-devflake at $DEVFLAKE_PATH
# - Registers it in the nix registry as "devflake"
# - Asks the user to pick an environment
# - Writes a minimal .envrc that does "use nix flakes devflake#<env>"
#
# DIRECTORY LOCATIONS
# - script_dir: Directory where the script is located
# - project_dir: Directory where the project will be created (eg OTHERFILES/project_dir/)
# - development_dir: Directory where the flake should be located (eg OTHERFILES/project_dir/.devflake/devflake)
# - project_name: Name of the project (eg my-project)
#
# This script is part of the Nix Devflake project:
# github.com/iansherr/nix-devflake
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/iansherr/nix-devflake/main/devflake-init.sh | bash
#
# =============================================================================
#


# Defaults
DEVFLAKE_BRANCH="main"
SCOPE="local"
: "${XDG_DATA_HOME:="$HOME/.local/share"}"

# --- Parse CLI args ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    -b|--branch)
      shift; DEVFLAKE_BRANCH="$1"; shift;;
    -s|--scope)
      shift; SCOPE="$1"; shift;;
    -h|--help)
      cat <<EOF
      Usage: $(basename "$0") [options]
      Options:
      -b, --branch <branch>   Git branch to clone/use (default: main)
      -s, --scope <scope>     Installation scope: local, project, or both (default: local)
      -h, --help              Show this help message
EOF
exit 0;;
*)
  echo "Unknown argument: $1" >&2; exit 1;;
esac
done

# Validate scope
if [[ ! "$SCOPE" =~ ^(local|project|both)$ ]]; then
  echo "Invalid scope: $SCOPE. Must be 'local', 'project', or 'both'." >&2
  exit 1
fi

# Paths
declare GLOBAL_PATH="$XDG_DATA_HOME/nix-devflake"
declare PROJECT_PATH="$(pwd)/.nix-devflake"

# --- Clone/update central devflake ---
if [[ "$SCOPE" == "local" || "$SCOPE" == "both" ]]; then
  echo "Updating central devflake at $GLOBAL_PATH (branch: $DEVFLAKE_BRANCH)"
  if [[ ! -d "$GLOBAL_PATH/.git" ]]; then
    git clone --branch "$DEVFLAKE_BRANCH" --single-branch \
      https://github.com/iansherr/nix-devflake.git "$GLOBAL_PATH"
  else
    (cd "$GLOBAL_PATH" && git fetch origin "$DEVFLAKE_BRANCH" && git checkout "$DEVFLAKE_BRANCH" && git pull --ff-only)
  fi
fi

# --- Clone/update project devflake ---
if [[ "$SCOPE" == "project" || "$SCOPE" == "both" ]]; then
  echo "Updating project devflake at $PROJECT_PATH (branch: $DEVFLAKE_BRANCH)"
  if [[ ! -d "$PROJECT_PATH/.git" ]]; then
    git clone --branch "$DEVFLAKE_BRANCH" --single-branch \
      https://github.com/iansherr/nix-devflake.git "$PROJECT_PATH"
  else
    (cd "$PROJECT_PATH" && git fetch origin "$DEVFLAKE_BRANCH" && git checkout "$DEVFLAKE_BRANCH" && git pull --ff-only)
  fi
fi

# Choose registry path (for path:// references)
if [[ "$SCOPE" == "project" || "$SCOPE" == "both" ]]; then
  REG_PATH="$PROJECT_PATH"
else
  REG_PATH="$GLOBAL_PATH"
fi

# --- Prompt for environment ---
declare -a ENVIRONMENTS=(python web rust go java sscript)
echo "Select your project environment:"
PS3="> "
select ENV in "${ENVIRONMENTS[@]}"; do
  [[ -n "$ENV" ]] && { ENVIRONMENT="$ENV"; break; }
  echo "Invalid choice; try again"
done

# --- Prompt for AI tooling ---
declare INCLUDE_AI=false
read -rp "Include AI tools? [y/N]: " AI_CHOICE
if [[ "$AI_CHOICE" =~ ^[Yy] ]]; then INCLUDE_AI=true; fi

# --- Generate .envrc with explicit path:// URIs ---
cat > .envrc <<EOF
# Project devShell configuration generated by devflake-init

# Primary environment:
use flake "path://${REG_PATH}#${ENVIRONMENT}"

# AI-enhanced environment (optional):
# use flake "path://${REG_PATH}#${ENVIRONMENT}-ai"
EOF

if [[ "$INCLUDE_AI" == true ]]; then
  cat >> .envrc <<EOF

# Loading AI-enhanced shell
use flake "path://${REG_PATH}#${ENVIRONMENT}-ai"
EOF
fi

cat >> .envrc <<EOF

# To update your devflake clone:
#   cd ${REG_PATH} && git pull && nix flake update
# Then reload:
#   direnv allow
EOF

#--- Finished ---
echo "✔ .envrc created for environment: $ENVIRONMENT${INCLUDE_AI:+ + AI}"
echo "Run 'direnv allow' to enter your project devShell"
